### ISSUE TITLE
Sublime Text: can not download with sync-setting package due to randomly changed "ignored_packages" list

### ISSUE THREAD

**Issue by rohan-paul** [mfuentesg/SyncSettings#120]
I am trying to download/install some 50+ packages with "Sync Settings. So, I do Preferences > Packages Settings > Sync Settings > Settings - and my User file contents is like below.

```
{
  /**
    * This token allow to plugin do:
    * - Create a Gist
    * - Download a Gist
    * - Upload a Gist
    * - Delete a Gist
   */
  "access_token": "54564545454545646465456+4651465",

  /**
   * Gist identifier for upload your configuration
   */
  "gist_id": "hd4554dsg45g5d4gjjmd54",

  /**
   * Download automagically the new version on ST startup
   */
  "auto_upgrade": false
}
```

 But it fails giving me the below error pop-up

 **It appears a package is trying to ignore itself, causing a loop.
    Please resolve by removing the offending ignored_packages setting.**

And then when I nevigate to Preference > Settings I see the below

```
{
	"ignored_packages":
	[
		"Vintage"
	]
}

```

I have looked throuh [this issue][2] , but could not resolve.

My system settings
Ubuntu - 18.04
Sublime Text - version 3.2 Build 3200

  [2]: https://github.com/SublimeTextIssues/Core/issues/2132

**Comment by shawnngtq** [comment]
I face the same error. For mine, it's related to GutterColor package. So I added `"*GutterColor.sublime-settings"` to the `excluded_files`. However, it did not resolve my error.

Do you have any solution / workaround?

@rohan-paul

**Comment by gknoop** [comment]
Am also having this issue, myself. Ubuntu 18.04.3.

**Comment by mfuentesg** [comment]
@gknoop

**Comment by mfuentesg** [comment]
Guys, if you still are facing issue, feel free reopen this issue.

**Comment by dhempy** [comment]
I am seeing this issue. My ignored packages are:

```
	"ignored_packages":
	[
		"Markdown",
		"Vintage"
	],
```

This seemed very much to be in a loop, with the dialog reappearing when I acknowledged it, about a dozen times. FWIW, at first it had two copies of the dialog overlapping. After clearing those 2-3 times, it then only showed one at a time.  Finally, Sublime exited without comment. 

I restarted Sublime, and none of my settings or packages seem to be in place. 

When I run Sync Settings Download again, it says "Downloading" for a few seconds, then "Downloaded". But, still no settings/packages are restored. 

I've rinsed and repeated a few times, with the same results. I have not seen the "ignored" warning since the first time. 

I guess I'll try un-ignoring (or just removing) those two packages and try again.

**Comment by dhempy** [comment]
Ok...a little more info...The two `ignored_packages` above were in the Sync gist. Removing those had no effect.

On my new computer, I went into User Preferences, and found (probably) all my packages in "ignored_packages". I removed that entire entry (and maybe restarted Sublime?), and now all my packages appear. Yay!

My theme/colors haven't come through...not sure if that's related.
