### ISSUE TITLE
Errno 20 Not a directory

### ISSUE THREAD

**Issue by tmdag** [mfuentesg/SyncSettings#138]
I've installed sync settings on 2 machines. Both of them share the exact same setup for 'sync settings' (same gist id, same token).
While one machine works fine - I can upload settings just fine
Second machine, when trying download - I am getting an error 
"Cannot perform this action due to network errors. reason: [Errno 20] Not a directory"

**Comment by FloLangenfeld** [comment]
Same here.
Don't know if that's related, but I was able to upload from a Windows 10 machine but not from an ubuntu-based distribution...
Just tried to download from the ubuntu computer, and it produced the same error: "Can't perform this action due to network errors. reason: [Errno 20] Not a directory"

Here is the error message the console output: [issue_138.txt](https://github.com/mfuentesg/SyncSettings/files/4118051/issue_138.txt)

**Comment by mfuentesg** [comment]
@tmdag @FloLangenfeld are you still facing this issue?

**Comment by mfuentesg** [comment]
checking the error, it is because “requests” package is not able to reach github domain (SSLError)

**Comment by tmdag** [comment]
it's been half a year from that error, and I've reinstalled sublime few times. Today I haven't got that error just yet

**Comment by mfuentesg** [comment]
So sorry, very occupied the last time. If you are facing the issue kindly close it.

**Comment by tmdag** [comment]
no worries, but it seems to be working so all good. Thanks!

**Comment by dawidof** [comment]
Got the same issue

**Comment by mfuentesg** [comment]
@dawidof Could you share your logs ?

**Comment by dawidof** [comment]
@mfuentesg I've got an empty file
![Screenshot 2021-02-02 at 13 59 54](https://user-images.githubusercontent.com/1425756/106603732-fb288500-655e-11eb-82db-493ddd8aed96.png)

**Comment by dawidof** [comment]
@mfuentesg could you help with this error?

**Comment by dawidof** [comment]
Found solution for this issue :)
![Screenshot 2021-02-13 at 20 38 46](https://user-images.githubusercontent.com/1425756/107859730-c4464f00-6e3b-11eb-9b6f-ab03bec4ddce.png)
